import ProjectPicker from '../../components/common/ProjectPicker.jsx';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { supabase } from '../../lib/supabase.js';
import { useModalDialog } from '../../hooks/useModalDialog.js';
import '../../styles/projects.css';
import '../../styles/project-monitoring.css';

const blank={projects:[],rows:[],updates:[]};
const statusColor=status=>({'Deployed':'green','Completed':'green','Ongoing':'yellow','In Progress':'yellow','For Review':'orange','On Hold':'gray','For QA':'purple','Active':'green'}[status]||'gray');
function dayOffset(date) {
 if(!date)return null;
 const today=new Date();return Math.round((Date.parse(`${date}T00:00:00Z`)-Date.UTC(today.getFullYear(),today.getMonth(),today.getDate()))/86400000);
}
const dateLabel=date=>date?new Date(`${date}T00:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'Not scheduled';
export default function ProjectMonitoringPage(){
 const [data,setData]=useState(blank),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [project,setProject]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[party,setParty]=useState('all'),[page,setPage]=useState(1),[dialog,setDialog]=useState(null);
 const request=useRef({version:0});
 const refresh=useCallback(async()=>{const version=++request.current.version;const result=await supabase.rpc('project_monitoring_snapshot');if(version!==request.current.version)return;if(result.error){setError(result.error.message);setData(blank);}else{setError('');setData(result.data||blank);}setLoading(false);},[]);
 useEffect(()=>{const requests=request.current;const initial=setTimeout(()=>{void refresh();},0);const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},15000);const focus=()=>{void refresh();};window.addEventListener('focus',focus);return()=>{requests.version++;clearTimeout(initial);clearInterval(timer);window.removeEventListener('focus',focus);};},[refresh]);
 const selected=data.projects.find(g=>g.id===project)||data.projects[0];
 const rows=data.rows.filter(r=>r.project_id===selected?.id);
 const latest=row=>data.updates.find(u=>u.row_id===row.id);
 const parties=[...new Set(rows.flatMap(r=>(r.pending_to||'').split(',').map(s=>s.trim()).filter(Boolean)))].sort();
 const filtered=rows.filter(r=>(status==='all'||r.status===status)&&(party==='all'||(r.pending_to||'').split(',').map(s=>s.trim()).includes(party))&&[r.ticket_no,r.custom_name,r.remarks,latest(r)?.summary].some(v=>String(v||'').toLowerCase().includes(query.toLowerCase())));
 const pages=Math.max(1,Math.ceil(filtered.length/9)),currentPage=Math.min(page,pages);
 const due=rows.filter(r=>!['Deployed','Completed'].includes(r.status)&&r.deployment_date).sort((a,b)=>a.deployment_date.localeCompare(b.deployment_date));
 const overdue=due.filter(r=>dayOffset(r.deployment_date)<0).length;
 const reset=(fn,value)=>{fn(value);setPage(1);};
 return <section className="module monitoring-module">
  <div className="monitoring-heading"><div><span className="monitoring-eyebrow">PROJECTS / MONITORING</span><h2>Project monitoring updates</h2><p>One clear view of progress, handoffs and what needs attention.</p></div><button className="secondary-btn" onClick={()=>{void refresh();}}><i className="fas fa-sync-alt" aria-hidden="true"/> Refresh</button></div>
  {error&&<p className="projects-error" role="alert">{error}</p>}
  {loading?<p role="status">Loading monitoring…</p>:!selected?<div className="monitoring-empty"><i className="fas fa-shield-alt" aria-hidden="true"/><h3>No Projects available for monitoring</h3><p>This workspace is available to the assigned Group POC, Head and Admin.</p></div>:<>
  <div className="monitoring-project-bar"><ProjectPicker projects={data.projects} selected={selected} onChange={id=>reset(setProject,id)}/><div><strong>{selected.client_name||selected.name}</strong><span className={`project-tier tier-${(selected.tier||'Standard').toLowerCase()}`}>{selected.tier}</span><small>Live Project data · {new Date().toLocaleDateString()}</small></div><Link to={`/projects?project=${selected.id}`} className="secondary-btn">Open project table <i className="fas fa-arrow-right" aria-hidden="true"/></Link></div>
  <div className="monitoring-stats">{[['Total items',rows.length,'layers'],['Deployed / completed',rows.filter(r=>['Deployed','Completed'].includes(r.status)).length,'check-circle'],['On hold',rows.filter(r=>r.status==='On Hold').length,'pause-circle'],['Past planned date',overdue,'clock']].map(([label,count,icon])=><div key={label}><i className={`fas fa-${icon==='layers'?'layer-group':icon}`} aria-hidden="true"/><strong>{count}</strong><span>{label}</span></div>)}</div>
  <div className="monitoring-overview"><div className="monitoring-panel"><h3>Status overview</h3>{[...new Set(rows.map(r=>r.status))].map(s=><button className="monitoring-status-line" key={s} onClick={()=>reset(setStatus,status===s?'all':s)} aria-pressed={status===s}><span className={`project-chip chip-${statusColor(s)}`}>{s}</span><span className="monitoring-meter"><span style={{width:`${rows.filter(r=>r.status===s).length/Math.max(rows.length,1)*100}%`}}/></span><strong>{rows.filter(r=>r.status===s).length}</strong></button>)}{!rows.length&&<p>No items yet.</p>}</div><div className="monitoring-panel"><h3>Deployment watch</h3><p className="monitoring-muted">Planned dates, excluding deployed and completed items.</p>{due.slice(0,5).map(r=>{const days=dayOffset(r.deployment_date);return <div className="monitoring-deadline" key={r.id}><div><strong>{r.ticket_no}</strong><span>{r.custom_name}</span></div><span className={`project-chip chip-${days<0?'orange':days<=7?'yellow':'teal'}`}>{days<0?`${-days}d past plan`:days===0?'Today':`${days}d remaining`}</span></div>;})}{!due.length&&<p>No upcoming deployment dates.</p>}{due.length>5&&<small>Showing the nearest 5 of {due.length} planned deployments.</small>}<small>{rows.filter(r=>!r.deployment_date&&!['Deployed','Completed'].includes(r.status)).length} active items without a planned date</small></div></div>
  <div className="monitoring-feed-heading"><div><h3>Latest item updates</h3><p>Latest summary first. Previous updates stay in history.</p></div><span>{filtered.length} items</span></div>
  <div className="monitoring-filters"><label>Search<input value={query} placeholder="Ticket, customization or update…" onChange={e=>reset(setQuery,e.target.value)}/></label><label>Status<select value={status} onChange={e=>reset(setStatus,e.target.value)}><option value="all">All statuses</option>{[...new Set(rows.map(r=>r.status))].map(s=><option key={s}>{s}</option>)}</select></label><label>Pending party<select value={party} onChange={e=>reset(setParty,e.target.value)}><option value="all">All parties</option>{parties.map(p=><option key={p}>{p}</option>)}</select></label></div>
  <div className="monitoring-cards">{filtered.slice((currentPage-1)*9,currentPage*9).map(row=>{const update=latest(row);return <article className="monitoring-card" key={row.id}><div className="monitoring-card-top"><span>{row.ticket_no} · {row.applied_to||'No applied company'}</span><span className={`project-chip chip-${statusColor(row.status)}`}>{row.status}</span></div><h4>{row.custom_name}</h4><div className="monitoring-card-meta"><span><i className="far fa-calendar" aria-hidden="true"/> {dateLabel(row.deployment_date)}</span><span>Pending: {row.pending_to||'Not specified'}</span></div><p className="monitoring-summary">{update?.summary||row.remarks||'No update posted yet.'}</p>{update?.next_action&&<div className="monitoring-next"><strong>Next action</strong><p>{update.next_action}</p>{update.follow_up_date&&<small>Follow up {dateLabel(update.follow_up_date)}</small>}</div>}<footer><small>{update?`Updated ${new Date(update.created_at).toLocaleDateString()}`:'From Project remarks'}</small><button className="secondary-btn" onClick={()=>setDialog({row,mode:'history'})}>History</button><button className="primary-btn" onClick={()=>setDialog({row,mode:'post'})}>Post update</button></footer></article>;})}</div>
  {!filtered.length&&<div className="monitoring-empty"><h3>No matching items</h3><p>Try another filter or add rows in the Project table.</p></div>}
  <div className="projects-pagination"><span>Page {currentPage} of {pages}</span><button className="secondary-btn" disabled={currentPage===1} onClick={()=>setPage(currentPage-1)}>Previous</button><button className="secondary-btn" disabled={currentPage===pages} onClick={()=>setPage(currentPage+1)}>Next</button></div>
  </>}
  {dialog&&data.rows.some(r=>r.id===dialog.row.id)&&<UpdateDialog dialog={dialog} updates={data.updates.filter(u=>u.row_id===dialog.row.id)} onClose={()=>setDialog(null)} onSaved={async()=>{setDialog(null);await refresh();}}/>}
 </section>;
}
function UpdateDialog({dialog,updates,onClose,onSaved}){
 const [summary,setSummary]=useState(''),[action,setAction]=useState(''),[date,setDate]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');const busy=useRef(false);const modal=useModalDialog(true,()=>{if(!busy.current)onClose();});
 const submit=async e=>{e.preventDefault();if(busy.current)return;busy.current=true;setSaving(true);setError('');try{const result=await supabase.rpc('project_monitoring_post',{p_row:dialog.row.id,p_summary:summary,p_next_action:action,p_follow_up:date||null});if(result.error)throw result.error;await onSaved();}catch(err){setError(err.message);}finally{busy.current=false;setSaving(false);}};
 return <div className="projects-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy.current)onClose();}}><div className="projects-dialog" {...modal}><div className="modal-header"><div><h3>{dialog.mode==='post'?'Post monitoring update':'Update history'}</h3><p>{dialog.row.ticket_no} · {dialog.row.custom_name}</p></div><button className="close-modal" aria-label="Close update dialog" disabled={saving} onClick={onClose}>×</button></div>{dialog.mode==='post'?<form onSubmit={submit}><fieldset className="projects-form" disabled={saving}><p>Post a concise summary for this item. Earlier updates remain in history.</p><label>Latest summary<textarea required maxLength={2000} rows={5} value={summary} onChange={e=>setSummary(e.target.value)} placeholder="What changed? What are we waiting for?"/></label><label>Next action<textarea maxLength={1000} rows={3} value={action} onChange={e=>setAction(e.target.value)} placeholder="Who needs to do what next?"/></label><label>Follow-up date (optional)<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{error&&<p className="projects-error" role="alert">{error}</p>}</fieldset><div className="modal-footer"><button type="button" className="secondary-btn" disabled={saving} onClick={onClose}>Cancel</button><button type="submit" className="primary-btn" disabled={saving}>{saving?'Posting…':'Post update'}</button></div></form>:<div className="monitoring-history"><details><summary>Current Project remarks</summary><p>{dialog.row.remarks||'No Project remarks.'}</p></details>{updates.length?updates.map(u=><article key={u.id}><small>{new Date(u.created_at).toLocaleString()}</small><p>{u.summary}</p>{u.next_action&&<p><strong>Next action: </strong>{u.next_action}</p>}{u.follow_up_date&&<small>Follow up {dateLabel(u.follow_up_date)}</small>}</article>):<p>No monitoring history yet. Current Project remarks appear on the overview.</p>}</div>}</div></div>;
}
