import test from 'node:test';
import assert from 'node:assert/strict';
import { PROJECT_ROW_FIELDS, parseProjectCSV } from '../src/utils/projectColumns.js';
import { stringifyCSV } from '../src/utils/csvHelpers.js';
const profiles=[{id:'user-a',username:'juan',is_active:true}];
const sample={ticket_no:'CST-001',custom_name:'Migration',client_name:'Wilcon',client_tier:'VVIP',applied_to:'Wilcon',system:'JPS',priority:'High',assigned_to:'@juan',assigned_dev:'Maria - external developer',assigned_qa:'Pedro',status:'Ongoing',is_signed:'No',deployment_date:'2026-10-15',pending_to:'Client',remarks:'Waiting, for "sign-off"\nNext meeting'};
const csv=rows=>stringifyCSV(PROJECT_ROW_FIELDS.map(([key])=>key),rows);
test('all fixed fields round trip, including multiline remarks and username assignment',()=>{const [row]=parseProjectCSV('\uFEFF'+csv([sample]),profiles,{client_name:'Project client',name:'Project name',tier:'VIP'});assert.equal(row.remarks,sample.remarks);assert.equal(row.assigned_to,'user-a');assert.equal(row.is_signed,false);assert.equal(row.client_name,'Project client');assert.equal(row.client_tier,'VIP');assert.equal(row.assigned_dev,'Maria - external developer');assert.equal(Object.keys(row).length,15);});
test('missing columns and duplicate tickets block the entire import',()=>{assert.throws(()=>parseProjectCSV('ticket_no\nCST-001',profiles),/Missing column/);assert.throws(()=>parseProjectCSV(csv([sample,{...sample,ticket_no:'cst-001'}]),profiles),/duplicate Ticket/);});
test('invalid date, inactive assignee and unknown enums are rejected',()=>{for(const changes of [{deployment_date:'2026-02-30'},{assigned_to:'missing'},{system:'UNKNOWN'}])assert.throws(()=>parseProjectCSV(csv([{...sample,...changes}]),profiles));});
test('malformed quotes and oversized batches are rejected',()=>{assert.throws(()=>parseProjectCSV('"ticket_no\nCST-001',profiles),/Unclosed/);assert.throws(()=>parseProjectCSV(csv(Array.from({length:201},(_,i)=>({...sample,ticket_no:`T-${i}`}))),profiles),/maximum of 200/);});

test('client columns from older CSV cannot override Project fields',()=>{const headers=[...PROJECT_ROW_FIELDS.map(([key])=>key),'client_name','client_tier'];const content=stringifyCSV(headers,[{...sample,client_name:'Wrong client',client_tier:'VVVIP'}]);const [row]=parseProjectCSV(content,profiles,{name:'Fallback project name',tier:'VVIP'});assert.equal(row.client_name,'Fallback project name');assert.equal(row.client_tier,'VVIP');});

test('priority header or value may be omitted and defaults to Medium',()=>{const headers=PROJECT_ROW_FIELDS.map(([key])=>key).filter(key=>key!=='priority');const [missing]=parseProjectCSV(stringifyCSV(headers,[sample]),profiles);assert.equal(missing.priority,'Medium');const [blank]=parseProjectCSV(csv([{...sample,priority:''}]),profiles);assert.equal(blank.priority,'Medium');});
test('spreadsheet systems, statuses and M/D/YYYY dates retain their meaning',()=>{const [row]=parseProjectCSV(csv([{...sample,system:'JPS, ESS',status:'Deployed',deployment_date:'9/16/2026'}]),profiles);assert.equal(row.system,'JPS, ESS');assert.equal(row.status,'Deployed');assert.equal(row.deployment_date,'2026-09-16');const [other]=parseProjectCSV(csv([{...sample,status:'For Review',deployment_date:'-'}]),profiles);assert.equal(other.status,'For Review');assert.equal(other.deployment_date,'');});
test('unmatched POC display names require explicit mapping rather than silent assignment',()=>{const content=csv([{...sample,assigned_to:'Dee Jay'}]);assert.throws(()=>parseProjectCSV(content,profiles),/must match one active user/);const [row]=parseProjectCSV(content,profiles,{}, {allowUnresolved:true});assert.equal(row.assigned_to,null);assert.equal(row._assigned_to_label,'Dee Jay');});
